# -*- coding: utf-8 -*-
"""geocoding.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YkcM9bQmACnGSgko0AoCCNmXEFtVTkqs
"""

!apt-get install -qq curl g++ make

!curl -L http://download.osgeo.org/libspatialindex/spatialindex-src-1.8.5.tar.gz | tar xz

import os
os.chdir('spatialindex-src-1.8.5')

!./configure

!make

!make install

!pip install rtree

!ldconfig

from rtree import index
from rtree.index import Rtree

pip install pandas geopandas geopy

from geopandas.tools import geocode
from geopy.geocoders import Nominatim
import pandas as pd
import geopandas as gpd
import geopy

data = pd.ExcelFile("/content/drive/MyDrive/Flexatel_probation/script/Portfolio2.xlsx")
df = pd.read_excel(data)

locator = Nominatim(user_agent="my_request")

# датафрэйм с нулевыми координатами
new_df = df[df['Y_LAT'].isnull()]

# геокодировали адреса, там где нулевые координаты. 
geocode = locator.geocode
new_df['location'] = new_df['address'].apply(geocode)
new_df['point'] = new_df['location'].apply(lambda loc: tuple(loc.point) if loc else None)

del new_df['Y_LAT']
del new_df['X_LON']
new_df = new_df.dropna()

new_df[['Y_LAT_x', 'X_LON_x', 'altitude']] = pd.DataFrame(new_df['point'].tolist(), index=df.index)

df = df.merge(new_df, on='name', how='left')

df['Y_LAT'] = df['Y_LAT'].fillna(df['Y_LAT_x']) 
df['X_LON'] = df['X_LON'].fillna(df['X_LON_x'])

new_gdf = gpd.GeoDataFrame(df, crs="EPSG:4326", geometry=gpd.points_from_xy(df.X_LON, df.Y_LAT))
new_gdf.plot()

russia = gpd.read_file('/content/drive/MyDrive/Flexatel_probation/script/admpol.shp')

russia_new = russia[['geometry', 'name']].to_crs('epsg:4326')

russia_new.plot()

adress = gpd.sjoin(new_gdf, russia_new)

adress = adress[['objecttype_x','Y_LAT','X_LON','name_left','storyes_x','material_x','address_x','name_right']]

adress.to_file('/content/drive/MyDrive/Flexatel_probation/adres_new.shp')